### PR TITLE
Website/saeed-IT-93

### PR DESCRIPTION
**Pull request by aworks2017**
A review request has been created for feature Website/saeed-IT-93

### CODE REVIEW

**Comment by jbadrov** [comment]
Rejected - need to fix email issue.

**Comment by jbadrov** [comment]
Rejected - need to fix email issue.

**Comment by aworks2017** [comment]
Rejected - need to fix email issue.

**Comment by aworks2017** [comment]
Rejected - need to fix email issue.

**Comment by aworks2017** [comment]
Rejected - need to fix email issue.

**Comment by aworks2017** [comment]
Rejected

**Comment by jbadrov** [comment]
Approved

**Comment by jbadrov** [comment]
Approved

**Comment by jbadrov** [comment]
Approved

**Comment by aworks2017** [comment]
Approved

**Pull request merged**
